# This file is autogenerated by the ./cabal2nix script.
# Re-run ./cabal2nix when the dependencies in the cabal
# file have changed.

{ mkDerivation, base, containers, directory, filepath, lvmlib, mtl
, network, parsec, process, stdenv, Top, transformers, wl-pprint
}:
mkDerivation {
  pname = "helium";
  version = "1.8.4";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    base containers directory filepath lvmlib mtl network parsec
    process Top transformers wl-pprint
  ];
  executableHaskellDepends = [
    base containers directory filepath lvmlib mtl network parsec
    process Top transformers wl-pprint
  ];
  homepage = "http://www.cs.uu.nl/wiki/bin/view/Helium/WebHome";
  description = "The Helium Compiler";
  license = "GPL";
}
