# This file is autogenerated by the ./cabal2nix script.
# Re-run ./cabal2nix when the dependencies in the cabal
# file have changed.

{ mkDerivation, base, bytestring, containers, directory, filepath
, lvmlib, mtl, network, parsec, process, stdenv, tasty, tasty-hunit
, Top, transformers, wl-pprint
}:
mkDerivation {
  pname = "helium";
  version = "1.8.4";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    base bytestring containers directory filepath lvmlib mtl network
    parsec process Top transformers wl-pprint
  ];
  executableHaskellDepends = [
    base containers directory filepath lvmlib mtl network parsec
    process Top transformers wl-pprint
  ];
  testHaskellDepends = [
    base bytestring containers directory filepath lvmlib mtl network
    parsec process tasty tasty-hunit Top transformers wl-pprint
  ];
  homepage = "http://www.cs.uu.nl/wiki/bin/view/Helium/WebHome";
  description = "The Helium Compiler";
  license = "GPL";
}
